### ISSUE TITLE
msbuild needed file not found

### ISSUE THREAD

**Issue by Tokimimo** [abalabahaha/zlib-sync#1]
**System information:**
Windows: 10
npm: 5.6.0
node: 8.11.3
node-gyp: 3.7.0
python: 2.7.5, 3.7

When trying to install zlib-sync I retrieve the following stacktrace 

````
PS C:\WINDOWS\system32> npm install zlib-sync

> zlib-sync@0.1.4 install C:\WINDOWS\system32\node_modules\zlib-sync
> node-gyp rebuild


C:\WINDOWS\system32\node_modules\zlib-sync>if not defined npm_config_node_gyp (node "D:\Programme\NodeJS\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Programme\NodeJS\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
MSBUILD : error MSB1009: Die Projektdatei ist nicht vorhanden.
Schalter: build/binding.sln
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Programme\NodeJS\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\Programme\\NodeJS\\node.exe" "D:\\Programme\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\WINDOWS\system32\node_modules\zlib-sync
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
````

As you can see I retrieve the error message MSB1009 from MSBUILD which indicates missing project files for/from zlib-sync.

I reinstalled node-gyp and windows-build-tools multiple times and verified that other projects like zlib and other are installable.

Do you know the cause for this error?

**Comment by abalabahaha** [comment]
Closing for inactivity, feel free to reopen.
